/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;
import java.awt.Color;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;


/**
 *
 * @author DELL ONE
 */
public class ventana extends javax.swing.JFrame implements MouseListener {
private JLabel[][] cuadros = new JLabel[3][3];
private boolean [] [] estados = new boolean [3][3];
int x = 8, y = 8;
    ImageIcon espacio = new ImageIcon(getClass().getResource("/icono/espacio.jpg"));
      ImageIcon aspa = new ImageIcon(getClass().getResource("/icono/aspa.jpg"));
        ImageIcon circulo = new ImageIcon(getClass().getResource("/icono/circulo.png"));
        int turno=0;
        int []contador = new int[4];
    /**
     * Creates new form ventana
     */
    public ventana (){
        initComponents();
       this.setLocationRelativeTo(null);
        InsetarCuadros();
    }
    void InsetarCuadros (){
        jPanel2.setLayout(null);
        for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                cuadros [i][j] = new JLabel();
                cuadros [i][j].setBounds(x, y, 130, 130);
                x += 138;
                cuadros [i][j].setIcon(espacio);
                estados [i][j] = false;
                jPanel2.add(this.cuadros[i][j]);
                cuadros [i][j].addMouseListener(this);
            }
                y +=138;
                x=8;
            }
    }
    void ganador(ImageIcon tipo){
        int k=2;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
               if(cuadros[i][i].getIcon() == tipo){
                  contador[0]++; 
               }
               if(cuadros[j][i].getIcon() == tipo){
                   contador[1]++;
               }
               if(cuadros[j][j].getIcon() == tipo){
                   contador [2]++;
               }
               if(cuadros[k][j].getIcon() == tipo){
                   contador [3]++;
               }
               k--;
            }
          if (contador[0]==3){   
              PintarCuadro(cuadros[i][0]);
              PintarCuadro(cuadros[i][1]);
              PintarCuadro(cuadros[i][2]);
              terminarjuego();
              break;
          }else if (contador[1]==3){   
              PintarCuadro(cuadros[0][i]);
              PintarCuadro(cuadros[1][i]);
              PintarCuadro(cuadros[2][i]);
              terminarjuego();
              break;
          }else if (contador[2]==3){   
              PintarCuadro(cuadros[0][0]);
              PintarCuadro(cuadros[1][1]);
              PintarCuadro(cuadros[2][2]);
              break;
          }else if (contador[3]==3){   
              PintarCuadro(cuadros[0][2]);
              PintarCuadro(cuadros[1][1]);
              PintarCuadro(cuadros[2][0]);
              terminarjuego();
              break;
          }else{
              contador[0]=0;
              contador[1]=0;
              contador[2]=0;
              contador[3]=0;
              k = 2;
          }
        }
    }
    void PintarCuadro(JLabel pintar){
        pintar.setBorder(new LineBorder(Color.yellow));
    }
    void terminarjuego(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (estados[i][j] == false) {
                    cuadros [i][j].setVisible(false);
                }
            }
  
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 41, 5, 384));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 400, 5));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 41, 5, 384));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 278, 400, 5));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 3, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel1");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 41, 5, 384));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 10, 400));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 3, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel1");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 41, 5, 384));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 10, 10, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
 public void mouseClicked(MouseEvent e){    
 }
    public void mousePressed(MouseEvent e){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
           if (e.getSource() == cuadros [i][j]){  
               if (estados[i][j] ==false){
                   turno ++;
                   if(turno %2 == 0){
                       cuadros[i][j].setIcon(circulo);
                   }else{
                       cuadros [i][j].setIcon(aspa);
                   }
                   estados[i][j]=true;
                   if (cuadros[i][j].getIcon() == circulo ){
                       ganador (circulo);
                   }else{
                      ganador (aspa); 
                   }
            }   
           }
 
        }
    }
   
 }
     @Override
    public void mouseReleased(MouseEvent e){
    }
    @Override
    public void mouseEntered (MouseEvent e){
    }
     @Override
    public void mouseExited(MouseEvent e){
        
    }
}